FROM centos-jdk8
MAINTAINER baoxiufeng

RUN adduser elasticsearch
ENV ELK_HOME /home/elasticsearch/elk
ENV ES_HOME $ELK_HOME/elasticsearch
ENV PATH $PATH:$ES_HOME/bin
ENV ES_VERSION 5.6.4
ENV ES_PKG_NAME elasticsearch-$ES_VERSION
ADD tars/$ES_PKG_NAME $ES_HOME

COPY config $ES_HOME/config

RUN set -ex; \
   chown -R elasticsearch:elasticsearch $ELK_HOME; \
   export ES_JAVA_OPTS='-Xms256m -Xmx256m'; \

WORKDIR $ES_HOME
CMD ["elasticsearch"]


