FROM openjdk:8-jre-alpine
MAINTAINER baoxiufeng

RUN addgroup -S elasticsearch && adduser -S -G elasticsearch elasticsearch
RUN apk update
RUN apk add --no-cache 'su-exec>=0.2' bash

ENV ES_HOME /usr/share/elasticsearch
ENV PATH $PATH:$ES_HOME/bin
WORKDIR $ES_HOME
ENV ES_VERSION 5.6.4
ENV ES_PKG_NAME elasticsearch-$ES_VERSION
ADD tars/$ES_PKG_NAME $ES_HOME

RUN set -ex; \
	# install normal components
	apk add --no-cache --virtual \
		ca-certificates \
		gnupg		\
		openssl		\
		tar		\
		openssh		\
		vim		\
		curl		\
	; \
	# create elaticsearch root directory
	mkdir -p ./plugins; \
	# loop to add authority
	for path in ./data ./logs ./config ./config/scripts \
	; do \
		mkdir -p "$path"; \
		chown -R elasticsearch:elasticsearch "$path"; \
	done; \

	# set jvm memory
	export ES_JAVA_OPTS='-Xms256m -Xmx256m'; \
	# print es version
	if [ "${ES_VERSION%%.*}" -gt 1 ]; then \
		elasticsearch --version; \
	else \
		elasticsearch -v; \
	fi
# copy config to container
COPY config ./config

VOLUME $ES_HOME/data
VOLUME $ES_HOME/logs

COPY docker-entrypoint.sh /
RUN chown -R elasticsearch:elasticsearch /docker-entrypoint.sh

# need to open es port
#EXPOSE $HTTP_PORT $TCP_PORT
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["elasticsearch"]
