FROM ubuntu:trusty
MAINTAINER baoxiufeng
# tag: bxf/ubuntu:trusty
RUN apt-get update; apt-get install -y unzip wget supervisor docker.io openssh-server
RUN echo 'root:baoxiufeng' | chpasswd
RUN mkdir /var/run/sshd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
