FROM bxf/centos-jdk8
MAINTAINER baoxiufeng
# tag: bxf/kafka-cluster

# set enviroment variables
ENV KAFKA_VERSION=1.0.0 \
    SCALA_VERSION=2.12 \
    KAFKA_HOME=/opt/kafka \
    PATH=${PATH}:${KAFKA_HOME}/bin

# install kafka
ADD ./kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz /opt/
ADD ./startKafkaCluster.sh ./startKafkaProducer.sh ./startKafkaConsumer.sh /usr/bin/
RUN ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka && \
    sed -i -r 's|broker\.id|#borker\.id|g' ${KAFKA_HOME}/config/server.properties && \
    sed -i -r 's|port=|#port=|g' ${KAFKA_HOME}/config/server.properties && \
    sed -i -r 's|log.dirs|#log\.dirs|g' ${KAFKA_HOME}/config/server.properties && \
    sed -i -r 's|zookeeper\.connect=|#zookeeper\.connect=|g' ${KAFKA_HOME}/config/server.properties && \
    mkdir -p ${KAFKA_HOME}/conf ${KAFKA_HOME}/data && \
    chmod +x /usr/bin/startKafka*.sh


# set container volumn directories
VOLUME ["${KAFKA_HOME}/conf", "${KAFKA_HOME}/data"]

# set container start shell
CMD sh /usr/bin/startKafkaCluster.sh

