FROM bxf/centos-jdk7
MAINTAINER baoxiufeng
# tag: bxf/zookeeper

# set enviroment variables
ENV ZK_VERSION=3.4.9

# install zookeeper
ADD ./zookeeper-${ZK_VERSION}.tar.gz /opt/
ENV ZK_HOME=/opt/zookeeper-${ZK_VERSION}
RUN mv ${ZK_HOME}/conf/zoo_sample.cfg ${ZK_HOME}/conf/zoo.cfg && \
    sed -i 's|/tmp/zookeeper|${ZK_HOME}/data|g' ${ZK_HOME}/conf/zoo.cfg; mkdir ${ZK_HOME}/data

# add zookeeper start shell to container
ADD ./startZk.sh /usr/bin/startZk.sh

# set zookeeper container default port mapping to host
EXPOSE 2181 2888 3888

# set container volumn directories
WORKDIR ${ZK_HOME}
VOLUME ["${ZK_HOME}/conf", "${ZK_HOME}/data"]

# set container start shell
CMD sh /usr/bin/startZk.sh

